### ISSUE TITLE
ReflectionException when dealing with payloads which are missing required keys

### ISSUE THREAD

**Issue by asaliev** [sunrise-php/hydrator#25]
PHP: **7.4.x**
Package version: **3.0.0**

If your your DTO is defined as follows:

```php
class MyDto
{
    private string $foo;
    
    public function getFoo(): string
    {
        return $this->foo;
    }
}
```

And you try to pass a payload which doesn't have the `foo` key, the following exception will be thrown, instead of `InvalidDataException`:

```
PHP Fatal error:  Uncaught ReflectionException: Cannot access non-public member MyDto::$foo in /path/to/vendor/sunrise/hydrator/src/Hydrator.php:159
```

According to the PHP documentation this is the expected behavior of `ReflectionProperty::isInitialized()` when you haven't called `ReflectionProperty::setAccessible(true)` on a private property prior to that.

I see that further down the code in the `hydrateProperty` method you actually do call `ReflectionProperty::setAccessible(true)`, maybe you could consider moving this further up the chain, somewhere just before the `ReflectionProperty::isInitialized()` call?

**Comment by fenric** [comment]
@asaliev #26

**Comment by fenric** [comment]
@asaliev https://github.com/sunrise-php/hydrator/releases/tag/v3.0.1
